// packages/angular/src/index.test-d.ts
/**
 * Angular adapter type-level inference tests. Compiled by `tsc --noEmit`;
 * never executed — bun's `*.test.ts` glob skips `*.test-d.ts`. Registered as a
 * knip entry so its exports are not flagged.
 */
import type { Signal } from "@angular/core";
import { layerKey } from "@stainless-code/layers";
import type { LayerCallContext, LayerState } from "@stainless-code/layers";

import { createStackHook, useMutationFlow, useStackHandles } from "./index";
import type { AppStack, LayerGroup, MutationFlow, StackHandles } from "./index";

/** Invariant mutual-assignability check. */
export type Equal<A, B> =
  (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2
    ? true
    : false;
export type Expect<T extends true> = T;

const removeKey = layerKey<boolean>()(["confirm", "remove"]);

declare const call: LayerCallContext<void, boolean>;
function _useMutationFlowShape() {
  return useMutationFlow(call);
}
export type _UseMutationFlowShape = Expect<
  Equal<ReturnType<typeof _useMutationFlowShape>, MutationFlow<boolean>>
>;
export type _MutationFlowPending = Expect<
  Equal<MutationFlow<boolean>["pending"], Signal<boolean>>
>;

function _useStackHandlesShape() {
  return useStackHandles("default", {});
}
export type _UseStackHandlesShape = Expect<
  Equal<ReturnType<typeof _useStackHandlesShape>, StackHandles>
>;
export type _StackHandlesStates = Expect<
  Equal<StackHandles["states"], Signal<LayerState[]>>
>;

declare const appStack: AppStack;
function openAppStackTagged() {
  return appStack.open({ key: removeKey, payload: { title: "Remove?" } });
}
export type _AppStackOpenInfersResponse = Expect<
  Equal<Awaited<ReturnType<typeof openAppStackTagged>>, boolean>
>;
function openAppStackPlain() {
  return appStack.open({ key: ["plain"], payload: { title: "hi" } });
}
export type _AppStackOpenPlainVoid = Expect<
  Equal<Awaited<ReturnType<typeof openAppStackPlain>>, void>
>;

declare const layerGroup: LayerGroup;
function openLayerGroupTagged() {
  return layerGroup.open({ key: removeKey, payload: { title: "Remove?" } });
}
export type _LayerGroupOpenInfersResponse = Expect<
  Equal<Awaited<ReturnType<typeof openLayerGroupTagged>>, boolean>
>;

declare const stackHook: ReturnType<typeof createStackHook>;
function openStackHookTagged() {
  return stackHook.useAppStack().open({
    key: removeKey,
    payload: { title: "Remove?" },
  });
}
export type _StackHookOpenInfersResponse = Expect<
  Equal<Awaited<ReturnType<typeof openStackHookTagged>>, boolean>
>;

// packages/solid/src/index.test-d.ts
import { layerKey, layerOptions } from "@stainless-code/layers";
import { useLayer, useLayerState } from "@stainless-code/solid-layers";
/**
 * Solid adapter type-level inference tests. Compiled by `tsc --noEmit`;
 * never executed — bun's `*.test.ts` glob skips `*.test-d.ts`. Registered as a
 * knip entry so its exports are not flagged.
 */
import type { Accessor } from "solid-js";

/** Invariant mutual-assignability check. */
export type Equal<A, B> =
  (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2
    ? true
    : false;
export type Expect<T extends true> = T;

/** Peel `Accessor<T>` for Solid adapter return assertions. */
type UnwrapAccessor<A> = A extends Accessor<infer T> ? T : never;

// A DataTag-branded key carries its response type end-to-end.
const removeKey = layerKey<boolean>()(["confirm", "remove"]);

type _SolidUseLayerStateTagged = ReturnType<
  typeof useLayerState<typeof removeKey>
>;
export type _SolidUseLayerStateTaggedResponse = Expect<
  Equal<
    NonNullable<UnwrapAccessor<_SolidUseLayerStateTagged>[number]>["response"],
    boolean | undefined
  >
>;
type _SolidUseLayerStatePlain = ReturnType<typeof useLayerState<["plain"]>>;
export type _SolidUseLayerStatePlainResponse = Expect<
  Equal<
    NonNullable<UnwrapAccessor<_SolidUseLayerStatePlain>[number]>["response"],
    void | undefined
  >
>;

const confirmOpts = layerOptions<{ title: string }, boolean>({
  key: ["confirm", "count"],
});

function openViaUseLayer() {
  const c = useLayer(confirmOpts);
  return c.open({ title: "n" });
}
export type _UseLayerOpenInfersResponse = Expect<
  Equal<Awaited<ReturnType<typeof openViaUseLayer>>, boolean>
>;
